name: System Initiative GitHub Action
description:
  Interact with the System Initiative workspace from within a GitHub Action
author: System Initiative
branding:
  icon: box
  color: black

# Define your inputs here.
inputs:
  workspaceId:
    description:
      The id of the workspace in which to interact. If this is not specified, we
      will retrive the workspaceId from the specific token used. If the
      workspaceId doesn't match the workspace the token is generated for then we
      will return an error.
    required: false
  changeSet:
    description: The name of the change set to create to make changes in.
    required: true
  componentId:
    description: The ID of the component to interact with.
    required: false
  component:
    description: The name of the component to interact with.
    required: false
  attributes:
    description: |
      A YAML or JSON object containing the attributes to set for component.

      For example:

      ```json
      attributes:
        /domain/Region: us-east-1
        BaseCidrBlock: 10.0.0.0/16
        Tags: ["tag1", "tag2"]
      ```

      You may specify property keys as names, property IDs, or paths (e.g. { "name/first": "John", "name/last": "Doe" }).

      Each property's value will be replaced with the new value. Properties not specified are left alone.

      If this is not specified, no properties will be set.
  managementFunction:
    description:
      The name of the management function to run. This is optional if the
      component only has one management function.
  applyOnSuccess:
    description:
      Whether to apply the change set to main after triggering the management
      function. Set to "force" to force apply (if your user has permission to do
      so).
    default: 'true'
  waitForApproval:
    description: Whether to wait for approval before applying the changeset (and
      fail if it is rejected).

      By default, we do not wait. If applyOnSuccess is anything but true (the
      default), this is ignored.

      If this is true, we will also wait for actions to complete unless you
      explicitly set waitForActions=false.
    default: 'false'
  waitForActions:
    description: Whether to wait for actions to complete (and fail if the
      actions fail).

      By default, we wait for actions if applyOnSuccess=force or
      waitForApproval=true--otherwise this setting is ignored.
    default: 'true'
  pollIntervalSeconds:
    description:
      Length of time (in seconds) between checks when polling for changeset
      status
    default: '10'

  apiToken:
    description: |
      The API token. You can create one by going to
      https://auth.systeminit.com/workspaces/, clicking on the Settings (gear)
      icon on your workspace, and selecting "API Tokens." Then enter a name and
      expiration, and click "Generate API Token."

      You should use GitHub's secrets mechanism to store and pass this.
    required: true

# Define your outputs here.
outputs:
  managementFunctionLogs:
    description: The logs from the management function.
  workspaceId:
    description: The ID of the workspace containing the component.
  changeSetId:
    description: The ID of the changeset created.
  changeSetWebUrl:
    description: The web URL to the changeset.
  componentWebUrl:
    description: The web URL to the component.

runs:
  using: node20
  main: 'dist/index.js'
