name: Continuous Integration

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v5
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Set dynamic date
        id: set-date
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "DATE=$DATE" >> "$GITHUB_ENV"
      - name: Test Local Action
        id: test-action
        uses: systeminit/actions@main
        with:
          changeSet: Testing Action - ${{ env.DATE }}
          componentId: 01JJFCNPEGPWFHARX2C3GW98XR
          domain: |
            Region: us-east-1
            BaseCidrBlock: 10.0.0.0/16
            BaseNamingConvention: GitHub Action
          applyOnSuccess: true
          apiToken: ${{ secrets.SI_API_TOKEN }}

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.managementFunctionLogs }}"
