on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  tag-major:
    name: Push release
    runs-on: ubuntu-latest
    steps:
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          publish_latest_tag: false
