name: Update dist files
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: npm install
      - run: npm run package
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: dist/**
          add_options: -u --force
          commit_message: 'chore(dist): Update dist [automated commit]'
          commit_user_name: SystemInit Bot
          commit_user_email: systeminit-bot@users.noreply.github.com
